from __future__ import annotations

from pathlib import Path
import subprocess


def write_task_note(repo_path: str, task_id: str, goal: str) -> str:
    notes_dir = Path(repo_path) / ".agent-orchestration"
    notes_dir.mkdir(parents=True, exist_ok=True)
    note_path = notes_dir / f"task-{task_id}.md"
    note_path.write_text(
        "# Task Note\n\n"
        f"- Task ID: `{task_id}`\n"
        f"- Goal: {goal}\n"
        "- Generated by manager for review and audit trail.\n",
        encoding="utf-8",
    )
    return str(note_path.relative_to(Path(repo_path)))


def detect_test_command(repo_path: str) -> str | None:
    p = Path(repo_path)
    if (p / "package.json").exists():
        return "npm test -- --watch=false"
    if (p / "pytest.ini").exists() or (p / "pyproject.toml").exists():
        return "pytest -q"
    return None


def run_shell(repo_path: str, command: str, timeout_seconds: int = 120) -> tuple[int, str]:
    completed = subprocess.run(
        command,
        cwd=repo_path,
        shell=True,
        capture_output=True,
        text=True,
        timeout=timeout_seconds,
    )
    output = ((completed.stdout or "") + "\n" + (completed.stderr or "")).strip()
    return completed.returncode, output
